CXX = g++ -g -std=c++20
FILES = obj/main.o obj/plant.o obj/primary.o obj/
EXE = PlantsVSZombie
all: $(EXE)

$(EXE) : $(FILES)
	$(CXX) $^ -o $@

obj/main.o : 
	$(CXX) -c $< -o $@


.PHONY : all clean

clean:
	rm -f $(FILES) $(EXE)